version: '3'
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    user: 204:204
    environment:
      TZ: America/Sao_Paulo
      LOG_LEVEL: debug
    volumes:
      - ./config:/app/config

networks:
  default:
    name: netmain
    external: true