- name: Start all containers
  gather_facts: false
  hosts: maine
  vars_prompt:
    - name: cftuntoken
      prompt: Cloudflare Tunnels token for maine
      private: false
    - name: cfapitoken
      prompt: Cloudflare API token for maine
      private: false

  tasks:
    - name: Pihole
      ansible.builtin.import_tasks: containers/pihole.ansible.yaml
    - name: Nextcloud
      ansible.builtin.import_tasks: containers/nextcloud.ansible.yaml
    - name: Proxies
      ansible.builtin.import_tasks: containers/proxies.ansible.yaml
