- name: Set up services
  gather_facts: false
  hosts: maine
  tasks:
    - name: Copy unbind-devices.service
      become: true
      ansible.builtin.copy:
        src: services/unbind-devices.service
        dest: /etc/systemd/system/unbind-devices.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable copied services
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        daemon_reload: true
        enabled: true
      with_items:
        - unbind-devices.service
