- name: Set up users
  hosts: maine
  tasks:
    - name: Set up group for proxies
      become: true
      ansible.builtin.group:
        name: proxies
        state: present
        gid: 200
        system: true
    - name: Set up user for proxies
      become: true
      ansible.builtin.user:
        name: proxies
        state: present
        uid: 200
        group: 200
        system: true
        create_home: false
        home: /nonexistant

    - name: Set up group for monitoring
      become: true
      ansible.builtin.group:
        name: monitoring
        state: present
        gid: 201
        system: true
    - name: Set up user for monitoring
      become: true
      ansible.builtin.user:
        name: monitoring
        state: present
        uid: 201
        group: 201
        system: true
        create_home: false
        home: /nonexistant

    - name: Set up group for Nextcloud
      become: true
      ansible.builtin.group:
        name: nextcloud
        state: present
        gid: 202
        system: true
    - name: Set up user for Nextcloud
      become: true
      ansible.builtin.user:
        name: nextcloud
        state: present
        uid: 202
        group: 202
        system: true
        create_home: false
        home: /nonexistant

    - name: Set up group for Jellyfin
      become: true
      ansible.builtin.group:
        name: jellyfin
        state: present
        gid: 203
        system: true
    - name: Set up user for Jellyfin
      become: true
      ansible.builtin.user:
        name: jellyfin
        state: present
        uid: 203
        group: 203
        system: true
        create_home: false
        home: /nonexistant

    - name: Set up group for Torrents
      become: true
      ansible.builtin.group:
        name: torrents
        state: present
        gid: 204
        system: true
    - name: Set up user for Torrents
      become: true
      ansible.builtin.user:
        name: torrents
        state: present
        uid: 204
        group: 204
        system: true
        create_home: false
        home: /nonexistant

    - name: Add Jellyfin to render group
      become: true
      ansible.builtin.user:
        name: jellyfin
        append: true
        groups:
          - render

    - name: Add tabby to libvirt group
      become: true
      ansible.builtin.user:
        name: tabby
        append: true
        groups:
          - libvirt
